version: '3'
services:
   webapp:
      image: "quay.io/cdis/jupyter-covid19:jupyter-covid1.1.12"
      volumes:
         - ${DATA_VOLUME}:/data
         - ${USER_VOLUME}:/home/jovyan/pd
      environment:
        - NAMESPACE=default
        - HOSTNAME=brh.data-commons.org
        - FRAME_ANCESTORS=https://brh.data-commons.org
      entrypoint:
        - "start-notebook.sh"
      command:
        - "--NotebookApp.base_url=/lw-workspace/proxy"
        - "--NotebookApp.default_url=/lab/tree/welcome.html"
        - "--NotebookApp.password=''"
        - "--NotebookApp.token=''"
      ports: 
         - "${SERVICE_PORT}:8888"
      healthcheck:
        test: ["CMD", "wget", "-O", "-", "http://localhost:8888/lw-workspace/proxy/lab/tree/welcome.html"]
        interval: 1m30s
        timeout: 10s
        retries: 3
      deploy:
        resources:
          limits:
            cpus: '1.00'
            memory: 1024M
          reservations:
            cpus: '0.5'
            memory: 512M
