# Which Identity Provider fence will/can use
#
# See ``fence/blueprints/login/__init__.py`` for which identity providers can
# be loaded.
#
ENABLED_IDENTITY_PROVIDERS:
  # ID for which of the providers to default to
  default: google
  # Information for identity providers
  providers:
# Additional Identity Provider options, simply uncomment:
#
#    orcid:
#      name: 'Login from ORCID'
#
    microsoft:
      name: Login from Microsoft
      secondary: true

#
#    fence:
#      name: 'Fence Multi-Tenant Login'
#
    google:
      name: 'Login from Google'
      secondary: true

# The following can be used for shibboleth login, simply uncomment.
#
# NOTE: Don't enable shibboleth if the deployment is not protected by
# shibboleth module, the shib module takes care of preventing header
# spoofing.
#
#    shibboleth:
#      name: 'NIH Login'
#

