#
# THIS IS AN AUTOGENERATED FILE (by gen3)
# root.tf is required for *terraform output*, *terraform taint*, etc
# @see https://github.com/hashicorp/terraform/issues/15761
#
terraform {
    backend "s3" {
        encrypt = "true"
    }
}
