name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: debug repo full_name output
        env:
          HEAD_REPO_FULL_NAME: ${{ github.event.pull_request['head']['repo']['full_name'] }}
        run: |
          echo "$HEAD_REPO_FULL_NAME"
      - name: automerge
        uses: "pascalgn/automerge-action@v0.13.1"
        if: github.event.pull_request['head']['repo']['full_name'] == 'uc-cdis/cdis-manifest'
        env:
          GITHUB_TOKEN: "${{ secrets.GEN3_RELEASE_GH_TOKEN || 'ignore' }}"
